### ISSUE TITLE
Post series plugin

### ISSUE THREAD

**Issue by sumobi** [pippinsplugins/theme#59]
I noticed the shortcode 101 posts weren't added to a series, however the series looked like they correctly included the right posts. The articles on the front end did not have "Part Of Series" label and you couldn't move from one to the next.

After reassigning them I noticed the series page is now showing double ups, which i've since fixed:

![screen shot 2014-12-27 at 2 48 57 pm](https://cloud.githubusercontent.com/assets/52581/5560100/9521f198-8dd7-11e4-8309-4826ad848db5.png)

Is this a bug you've seen before? Sounds like the one you noted one the other day.

We should consider either building that plugin from scratch, fixing any current bugs, or switching to to a new plugin.

**Comment by pippinsplugins** [comment]
See #65
