### ISSUE TITLE
Account page needs some love

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/theme#69]
The purchase history especially is in need of some love:

![screen shot 2015-01-30 at 10 26 53 am](https://cloud.githubusercontent.com/assets/1034109/5979133/9cfe4fee-a86a-11e4-866c-cbd580f11805.png)

It also appears that something in the theme has broken the View Licenses link.

**Comment by sumobi** [comment]
2016 is the year to get better at checking my notifications. Here's how the new tabbed account page is looking so far:

![screen shot 2016-01-03 at 7 43 33 pm](https://cloud.githubusercontent.com/assets/52581/12077617/891dbbca-b252-11e5-986b-58899ede3c1c.png)

**Comment by sumobi** [comment]
@pippinsplugins Slight tweak to design to be more consistent with site styling:

![screen shot 2016-01-03 at 11 11 03 pm](https://cloud.githubusercontent.com/assets/52581/12078256/5ef5cbb8-b26f-11e5-8095-eda6d3cbdc0c.png)

Also implemented jQuery BBQ so we can link customers to individual tabs in support if need be.

The only thing missing is the pro add-ons for the "extras" section. Want me to remove the extras tab for now, and make the changes live?

**Comment by pippinsplugins** [comment]
Looks great!

Yes, let's go ahead and remove extras tag until we are ready to go live
with that.

**Comment by sumobi** [comment]
New tab layout is live

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pippinsplugins** [comment]
Looks excellent!
