### ISSUE TITLE
Add testimonials to product sidebar

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/theme#70]
We should have testimonials here: https://cloudup.com/cUcfOpdFAsJ

**Comment by pippinsplugins** [comment]
First testimonial:

"None of the other membership plugins even come close to RCP when it comes to adhering to WordPress principals, coding best practices, and general usability best practices. http://www.wpsitecare.com/best-wordpress-plugins/"

**Comment by sumobi** [comment]
Closing this since RCP on pp.com now links to the new site.
