### ISSUE TITLE
Add RCP banner to sidebar

### ISSUE THREAD

**Issue by pippinsplugins** [pippinsplugins/theme#72]
We should add RCP to the sidebar: 
![screen shot 2015-12-29 at 1 50 56 pm](https://cloud.githubusercontent.com/assets/1034109/12041019/4aa4a458-ae33-11e5-8f6d-cdee95ef9aa5.png)

**Comment by sumobi** [comment]
@pippinsplugins I've always wondered, do they actually work? we should track them a bit better. We might see similar results to http://www.carriedils.com/the-great-affiliate-experiment/ and should just remove them altogether.

**Comment by pippinsplugins** [comment]
@sumobi Good point. How about adding UTM links to them so we can see how well they work?

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
lol? https://github.com/pippinsplugins/theme/issues/64#issuecomment-68265010

**Comment by sumobi** [comment]
<img width="361" alt="screen shot 2016-01-29 at 9 38 50 pm" src="https://cloud.githubusercontent.com/assets/52581/12670909/f63c814a-c6d0-11e5-9f0b-d80c12bf6454.png">

UTM links look ok to you @pippinsplugins?

**Comment by pippinsplugins** [comment]
Perfect.
