### ISSUE TITLE
Missing argument 2 for affwp_show_the_title()

### ISSUE THREAD

**Issue by mindctrl** [pippinsplugins/theme#74]
Seeing a ton of these in the error log.

`PHP Warning:  Missing argument 2 for affwp_show_the_title(), called in /wordpress-4.7.5/wp-includes/class-wp-hook.php on line 298 and defined in /dom6899/wp-content/themes/pippinsplugins-30/includes/custom-filters.php on line 58`

**Comment by mindctrl** [comment]
Still seeing a ton of these. So many that it's hard to look for other errors in the log file.

**Comment by pippinsplugins** [comment]
Hmmm, that is here https://github.com/pippinsplugins/theme/blob/21df20be203405e5e17d5c70f899075d4c0f29da/includes/custom-filters.php#L58

I don't see any issues there....

**Comment by amdrew** [comment]
Will track it down

**Comment by amdrew** [comment]
Couldn't replicate locally or on site but made a slight tweak to hopefully fix it. Will keep an eye on the logs.

**Comment by amdrew** [comment]
Not seeing any more errors, closing
